### ISSUE TITLE
cleanup ext_localconf.php

### ISSUE THREAD

**Issue by tomasnorre** [AOEpeople/asdis#4]
Create backend/Utility Class to cleanup ext_localconf.php

* Backend/Utility/HooksUtility.php
* Backend/Utility/ScrapersUtility.php
* Backend/Utility/FiltersUtility.php

Where we registers the respective types, and have the ext_localconf.php cleaner.

**Comment by tomasnorre** [comment]
@StefanMasz I would go with namespaced classes here?
What do you say? Would you stick to Tx_Asdis or add new files with namespace ?

**Comment by StefanMasz** [comment]
@tomasnorre I added the last files with tx_ because some teammates didnt like mixed naming conventions. But when you are fine with that make it with namespaces. These teammates do not Work on the code at the moment. ;-)

**Comment by tomasnorre** [comment]
@StefanMasz  
Ok. I'll add them with Namespace and create a follow up to convert to namespace and PSR-2 ok?
